1. Suppose you have a dataset containing daily temperature readings for a city, and you want to identify days with extreme temperature conditions. Find days where the temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees Celsius (cold day). 
Input: temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])

In [9]:
import numpy as np
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])
hot_days_indices = np.where(temperatures >35)
cold_days_incdices = np.where(temperatures <5)
hot_days = temperatures[hot_days_indices]
cold_days = temperatures[cold_days_incdices]
print("Hot days(temperatures >35°C):",hot_days)
print("Cold days (temperature < 5°C):",cold_days)

Hot days(temperatures >35°C): [36.8 38.7 37.2]
Cold days (temperature < 5°C): []


2. Suppose you have a dataset containing monthly sales data for a company, and you want to split this data into quarterly reports for analysis and reporting purposes. 

Input: monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

In [13]:
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])
quartely_sales = monthly_sales.reshape(4,3)
print("Quarterly sales data: \n",quartely_sales)

Quarterly sales data: 
 [[120 135 148]
 [165 180 155]
 [168 190 205]
 [198 210 225]]


3. Suppose you have a dataset containing customer data, and you want to split this data into two groups: one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days. 

Input: customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110]) 

last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])


In [19]:
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
recent_purchases = customer_ids[last_purchase_days_ago > 30]
non_recent_purchasers = customer_ids[last_purchase_days_ago > 30]
print("Recent purchasers (last 30 days):",recent_purchases)
print("Non-recent purchasers:", non_recent_purchasers)

Recent purchasers (last 30 days): [106 107 108 109 110]
Non-recent purchasers: [106 107 108 109 110]


4.Suppose you have two sets of employee data—one containing information about full-time employees and another containing information about part-time employees. You want to combine this data to create a comprehensive employee dataset for HR analysis. Input: # Employee data for full-time employees full_time_employees = np.array([ [101, 'John Doe', 'Full-Time', 55000], [102, 'Jane Smith', 'Full-Time', 60000], [103, 'Mike Johnson', 'Full-Time', 52000] ])
# Employee data for part-time employees part_time_employees = np.array([ [201, 'Alice Brown', 'Part-Time', 25000], [202, 'Bob Wilson', 'Part-Time', 28000], [203, 'Emily Davis', 'Part-Time', 22000] ])


In [21]:
full_time_employees = np.array([ [101, 'John Doe', 'Full-Time', 55000], [102, 'Jane Smith', 'Full-Time', 60000], [103, 'Mike Johnson', 'Full-Time', 52000] ])
part_time_employees = np.array([ [201, 'Alice Brown', 'Part-Time', 25000], [202, 'Bob Wilson', 'Part-Time', 28000], [203, 'Emily Davis', 'Part-Time', 22000] ])
employee_data = np.vstack((full_time_employees, part_time_employees))
print("Comprehensive employee dataset:\n",employee_data)

Comprehensive employee dataset:
 [['101' 'John Doe' 'Full-Time' '55000']
 ['102' 'Jane Smith' 'Full-Time' '60000']
 ['103' 'Mike Johnson' 'Full-Time' '52000']
 ['201' 'Alice Brown' 'Part-Time' '25000']
 ['202' 'Bob Wilson' 'Part-Time' '28000']
 ['203' 'Emily Davis' 'Part-Time' '22000']]
