1. Create a 1D array with elements from 1 to 10.

In [1]:
import numpy as np 
arr1 = np.arange(1,11)
print("1D array:",arr1)

1D array: [ 1  2  3  4  5  6  7  8  9 10]


2. Create a 2D array of size 3x3 filled with zeros.

In [3]:
arr2 = np.zeros((4,4))
print("2D array of zeros:\n",arr2)

2D array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. Find the maximum and minimum values in an array.

In [9]:
max_value = np.max(arr1)
min_value = np.min(arr1)

print("array :: ",arr1)
print(" maximum values ::",max_value)
print(" minimum values ::",min_value)

array ::  [ 1  2  3  4  5  6  7  8  9 10]
 maximum values :: 10
 minimum values :: 1


4. Reshape a 1D array into a 2D array of shape 2x5.

In [11]:
array_reshaped = arr1.reshape(2,5)
print("original 1d array:",arr1)
print("reshaped 2d array:\n",array_reshaped)

original 1d array: [ 1  2  3  4  5  6  7  8  9 10]
reshaped 2d array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


5. Generate a 1D array of 5 random integers between 10 and 50.

In [13]:
random_array = np.random.randint(10,50,5)
print("random array:", random_array)

random array: [22 26 38 49 38]


6. Convert the below list into numpy array then display the array
Input: my_list = [1, 2, 3, 4, 5]

In [15]:
my_list = [1,2,3,4,5]
array_from_list = np.array(my_list)
print("array from list:",array_from_list)

array from list: [1 2 3 4 5]


7. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.
Input: my_list = [1, 2, 3, 4, 5]

In [17]:
my_list = [1,2,3,4,5]
array_from_list = np.array(my_list)
print("array from list:",array_from_list)
first_element = array_from_list[0]
last_element = array_from_list[-1]
print("first Element:",first_element)
print("last Element: ",last_element)
multiplied_array = array_from_list * 2
print("array multiplied by 2:",multiplied_array)

array from list: [1 2 3 4 5]
first Element: 1
last Element:  5
array multiplied by 2: [ 2  4  6  8 10]
